"""Change created_by to integer user_id

Revision ID: 0a779aab2611
Revises: 0bb9fc6eaee6
Create Date: 2025-10-09 17:32:43.355110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a779aab2611'
down_revision: Union[str, Sequence[str], None] = '0bb9fc6eaee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
