"""Initial migration

Revision ID: 0bb9fc6eaee6
Revises: 
Create Date: 2025-10-09 17:10:25.398546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb9fc6eaee6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_chats', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(None, 'group_chats', type_='foreignkey')
    op.create_foreign_key(None, 'group_chats', 'users', ['created_by'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_chats', type_='foreignkey')
    op.create_foreign_key(None, 'group_chats', 'users', ['created_by'], ['id'])
    op.alter_column('group_chats', 'created_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
